#!/bin/sh
#/usr/lib/systemd/system-sleep/power-tune

# Disable power button wakeup
echo disabled | sudo tee /sys/bus/platform/devices/axp20x-pek/power/wakeup 

# Disable USB wakeup
for path in $(find /sys/devices -type f -name wakeup | grep -i usb); do
    [[ -w "$path" ]] && echo disabled > "$path"
done

# WiFi state check + toggle logic (Disable, if enabled to prevent lockup)
wifi_state=$(rfkill -n -o TYPE,SOFT | grep wlan | awk '{print $2}')

if [ "$wifi_state" = "unblocked" ]; then
    sudo systemctl stop NetworkManager
    sudo systemctl disable NetworkManager
    sudo rfkill block wlan
else
    sudo rfkill unblock wlan
    sudo systemctl enable NetworkManager
    sudo systemctl start NetworkManager
    sleep 5
fi

case "$1" in
 pre) 
     ip link set wlan0 down 
 ;; 
 post) 
     ip link set wlan0 up 
 ;; 
esac
